name: Run Checker
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetchy:
    name: Check Milford Track
    runs-on: ubuntu-latest
    env:
      PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.13.1
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test
      - uses: actions/upload-artifact@v2
        with:
          name: screenshot.png
          path: screenshot.png
